# Generated by Django 2.1 on 2021-10-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='partner_corporate_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
