# Generated by Django 2.0.7 on 2018-09-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='localcompanies',
            field=models.ManyToManyField(through='contract_index.IndexLocalCompany', to='contract_index.LocalCompany'),
        ),
    ]
