# Generated by Django 2.1 on 2021-02-08 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contract_index', '0003_auto_20190514_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='contract_companies',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='index',
            name='contract_termination_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='index',
            name='document_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='loan_guarantee_availability',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='original_classification',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='original_storage_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='ringi_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='ringi_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='storage_location_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='indexlocalcompany',
            name='add_flg',
            field=models.BooleanField(default=False),
        ),
    ]
